Search UI refinements
1ifeworld/river pull request #229
Opened 2023-09-14 17:34 UTC by tangerine-orange

1. 
**Problem:** When adding an nft to a Channel, `SearchContainer` displays an empty preview (`SearchGallery`) as soon as the `AddToChannelModal` opens. This is confusing as a user. Am I supposed to set the Title, Created By, etc?
**Solution:** Don't render the preview (`SearchGallery`) until we have a search result

before:
<img width="545" alt="Screen Shot 2023-09-14 at 1 32 42 PM" src="https://github.com/1ifeworld/river/assets/83888516/19fd63d6-1c47-4422-8e89-4a29892c97c0">

after:
<img width="483" alt="Screen Shot 2023-09-14 at 1 33 31 PM" src="https://github.com/1ifeworld/river/assets/83888516/27d7fe43-58ab-432b-a83e-51029706051b">
<img width="482" alt="Screen Shot 2023-09-14 at 1 33 47 PM" src="https://github.com/1ifeworld/river/assets/83888516/8f99912c-6ad6-4f81-8f35-b92124e965ef">

2.
**Problem:** In the same flow, the Add button should be disabled until we have a search result. Currently, we are checking the existence of `searchConfig` but it makes more sense to check for `searchResults`.

2023-09-14 17:44 UTC, 0xTranqui commented
@tangerine-orange this is so cool to see a potential contrib here!! im gonna authroize ur commit so we can deploy the preview, and then will provide feedback/comments on ur pr after

2023-09-14 17:45 UTC, 0xTranqui commented
here's what the proposed changed looks like on a live deploy so ppl have a better image of this pr in their heads

<img width="1512" alt="Screenshot 2023-09-14 at 1 45 02 PM" src="https://github.com/1ifeworld/river/assets/93691906/af1c6436-7aed-46ca-a7c2-c46c6ea2556a">

2023-09-14 17:58 UTC, 0xTranqui requested changes
Ok here's a few disparate thoughts + comments:

1. the reason addReady is dependent on sendDataConfig atm is because it unsures that the wagmi usePrepareContractWrite is being done correctly and will properly trigger a transaction request when the button is clicked. I like what you've done by adding searchResults as a dep as well, but would suggest we change change this to be `!!searchResults && !!sendDataConfig`

2. in terms of the change to the UI, i think its an interesting direciton and agree could reduce end user confusion of what action is supposed to happen there. before merging this section, do you thiink you could try to implement a version where the gallery bit renders below the search instead of above it? I think that could make more sense so that the SearchInput doesnt jump around after the target metadata is rendered

overall am a fan of the simple + reason based edits you are suggesting

2023-09-14 19:17 UTC, tangerine-orange commented
> 2. in terms of the change to the UI, i think its an interesting direciton and agree could reduce end user confusion of what action is supposed to happen there. before merging this, do you think you could try to implement a version where the gallery section renders below the search input instead of above it? Not 100% sure if this would be better, but think it could possibly make more sense so that the SearchInput doesnt jump around after the target metadata is rendered

Your thoughts make sense. Rendering gallery below input is also jumpy.

The goal here is to give the user affordance that they are supposed to type into the inputs, so there should be other ways to do this other than just not rendering the gallery like I did in this branch.

Here's another idea:
https://github.com/1ifeworld/river/assets/83888516/3093002c-3208-41d5-837a-62eeae885255
1. Make "Title" a `text-label-muted` if there is no `nftMetadata`
2. Autofocus the contract address Input
3. Put border around the NFT cell inside the gallery

Do you like any or all of these changes?

When I first tried to add an NFT to the channel, I was confused, I didn't know what I was supposed to do. Thus, this PR. It's hard to put myself back in the mindset that I was in then, but I think this new version would probably fix it.

2023-09-14 20:53 UTC, tangerine-orange commented
> Here's another idea: https://github.com/1ifeworld/river/assets/83888516/3093002c-3208-41d5-837a-62eeae885255

And these changes, but with the gallery below:
![Screen Shot 2023-09-14 at 4 52 52 PM](https://github.com/1ifeworld/river/assets/83888516/0aca72a2-8726-4c12-a9e4-41636e362a4a)

2023-09-14 20:56 UTC, salieflewis commented
> > 2. in terms of the change to the UI, i think its an interesting direciton and agree could reduce end user confusion of what action is supposed to happen there. before merging this, do you think you could try to implement a version where the gallery section renders below the search input instead of above it? Not 100% sure if this would be better, but think it could possibly make more sense so that the SearchInput doesnt jump around after the target metadata is rendered
> 
> Your thoughts make sense. Rendering gallery below input is also jumpy.
> 
> The goal here is to give the user affordance that they are supposed to type into the inputs, so there should be other ways to do this other than just not rendering the gallery like I did in this branch.
> 
> Here's another idea: https://github.com/1ifeworld/river/assets/83888516/3093002c-3208-41d5-837a-62eeae885255
> 
> 1. Make "Title" a `text-label-muted` if there is no `nftMetadata`
> 2. Autofocus the contract address Input
> 3. Put border around the NFT cell inside the gallery
> 4. Give NFT cell white background when it's populated with a search result (leave it gray otherwise)
> 
> Do you like any or all of these changes?
> 
> When I first tried to add an NFT to the channel, I was confused, I didn't know what I was supposed to do. Thus, this PR. It's hard to put myself back in the mindset that I was in then, but I think this new version would probably fix it.

I think this makes sense

> > Here's another idea: https://github.com/1ifeworld/river/assets/83888516/3093002c-3208-41d5-837a-62eeae885255
> 
> And these changes, but with the gallery below: ![Screen Shot 2023-09-14 at 4 52 52 PM](https://user-images.githubusercontent.com/83888516/268108926-0aca72a2-8726-4c12-a9e4-41636e362a4a.png)

What would it look like to put the gallery between but keep the input up at the top? I like this idea and I think the component definitely needs work to make it feel more intuitive. This is a great start. 

In particular what frustrates me about the UX surrounding it is the need to search a component and then add it to your channel, as part of a two step process.

2023-09-14 21:45 UTC, tangerine-orange commented
@salieflewis I like that idea:
<img width="1094" alt="Screen Shot 2023-09-14 at 5 44 46 PM" src="https://github.com/1ifeworld/river/assets/83888516/b9e9c389-e116-4c1c-bee9-20d87e37287a">
<img width="1085" alt="Screen Shot 2023-09-14 at 5 44 51 PM" src="https://github.com/1ifeworld/river/assets/83888516/161b55a1-9d5a-4099-b475-f94c7691e970">


If you like this, I'll update the branch to reflect it

2023-09-15 02:18 UTC, salieflewis commented
> @salieflewis I like that idea: <img alt="Screen Shot 2023-09-14 at 5 44 46 PM" width="1094" src="https://user-images.githubusercontent.com/83888516/268118574-b9e9c389-e116-4c1c-bee9-20d87e37287a.png"> <img alt="Screen Shot 2023-09-14 at 5 44 51 PM" width="1085" src="https://user-images.githubusercontent.com/83888516/268118583-161b55a1-9d5a-4099-b475-f94c7691e970.png">
> 
> If you like this, I'll update the branch to reflect it.
> 
> I think this UI suggests a future where you can search for a contract without specifying token ID, and then you can select multiple from that collection and add them in batch.

Going to bring the person in who created these designs in the first place to weigh in on this, personally I'm happy with this approach for now. Although if we were to change the UI in this way we may have to introduce a bottom border on the `StateNav` component because the horizontal nav doesn't look the same without the bounding box of the gallery component.

cc: @ioeylim 

I think in future @tangerine-orange we should develop a contribution process where we create a well scoped issue for changes, especially if they're UI/design related such that we don't need to be designing on the fly in the context of a PR. Thanks for your interest in contributing and flexibility nonetheless!

2023-09-16 19:40 UTC, RANJEETJ06 commented
@salieflewis can you tell mw how to setup locally this project '@river/design-system' giving error how to install/setup it

2023-09-16 19:49 UTC, salieflewis commented
> @salieflewis can you tell mw how to setup locally this project '@river/design-system' giving error how to install/setup it

Can you create a separate issue where you describe exactly what errors you're running into when running the codebase locally.

2023-09-16 20:07 UTC, RANJEETJ06 commented
> > @salieflewis can you tell mw how to setup locally this project '@river/design-system' giving error how to install/setup it
> 
> Can you create a separate issue where you describe exactly what errors you're running into when running the codebase locally.

#247

2023-09-19 17:28 UTC, ioeylim commented
> @salieflewis I like that idea: <img alt="Screen Shot 2023-09-14 at 5 44 46 PM" width="1094" src="https://user-images.githubusercontent.com/83888516/268118574-b9e9c389-e116-4c1c-bee9-20d87e37287a.png"> <img alt="Screen Shot 2023-09-14 at 5 44 51 PM" width="1085" src="https://user-images.githubusercontent.com/83888516/268118583-161b55a1-9d5a-4099-b475-f94c7691e970.png">
> 
> If you like this, I'll update the branch to reflect it.
> 
> I think this UI suggests a future where you can search for a contract without specifying token ID, and then you can select multiple from that collection and add them in batch.

There was a lot of great insights here, thank you for bringing them to our attention. 

I agree with you that it's not the most intuitive approach currently. So small things like the add button being disabled before searching a piece goes a long way. But more broadly, I think the design may need a bigger overhaul than just the interactive features. Will be taking your comments into consideration when we tackle this feature again soon.

2023-09-20 13:43 UTC, salieflewis commented
On @ioeylim's note, I'm going to go ahead and close this. Hope this is not discouraging @tangerine-orange, and forgive us for the back and forth as we still are working through our contribution process.

Perhaps you'll find interest in tackling one of the open issues?

2023-09-20 13:43 UTC, closed without merging