custom progress comp, rename dropzone to item dropzone
1ifeworld/river pull request #340
Opened 2024-01-18 18:36 UTC by salieflewis

2024-01-18 22:40 UTC, 0xTranqui requested changes
left a few comments. main thing i think that would be good to touch up is some of the exemption handling, particularly in terms of the toasts that may pop up for a user if something goes wrong

2024-01-18 22:40 UTC, 0xTranqui commented on apps/site/components/client/ItemDropzone.tsx
> +      if (signMessage && targetUserId) {
i think we want some better exemption/error handling for things that might happen like line 100. what happens if it gets to this point but then those things arent there? some of the newer txnSuccess based try catch logic with different versions of toasts might be helpful here! I had implemented them all around the site EXCEPT the dropzone component bc it had been getting worked on. u can see an example of it in the channel dialog [component](https://github.com/1ifeworld/river/blob/main/apps/site/components/client/ChannelDialog.tsx)

2024-01-18 22:47 UTC, salieflewis commented on apps/site/components/client/ItemDropzone.tsx
> +
Feel like the file is a bit crazy so I'm not mad at splitting it out.

2024-01-19 02:42 UTC, 0xTranqui approved these changes

2024-01-19 02:44 UTC, merged