owner check to address issue#346
1ifeworld/river pull request #357
Opened 2024-01-21 22:43 UTC by jawndiego

2024-01-21 22:54 UTC, jawndiego commented
resolves #346

2024-01-23 17:06 UTC, 0xTranqui requested changes
i think theres a bit more handling to do on the new ternary logic but besides that looks good!

2024-01-23 17:06 UTC, 0xTranqui commented on apps/site/components/client/Header.tsx
> +        const owner = user.wallet ? user.wallet.address : null
what happens in this null case? do we want to add an if check before this to prevent possibility of `user.wallet` not existing? will the user then be prompted again to enter an email to regenerate a private key? a bit more handling/structure around this then i think good to go!

2024-01-23 17:08 UTC, 0xTranqui commented on apps/site/components/client/Header.tsx
> +        const owner = user.wallet ? user.wallet.address : null
like lets not even let the modal open/state progress forward (or something like that) if user.wallet.address doesnt exist

2024-01-23 17:08 UTC, 0xTranqui commented on apps/site/components/client/Header.tsx
> +        const owner = user.wallet ? user.wallet.address : null
or perhaps this is unncessary all together because `isNewUser` being true means by definition there is an associated user.wallet.address detected?

2024-01-23 17:09 UTC, 0xTranqui commented on apps/site/components/client/Header.tsx
> +        const owner = user.wallet ? user.wallet.address : null
cc @jawndiego

2024-01-29 00:32 UTC, 0xTranqui commented
<img width="440" alt="Screenshot 2024-01-28 at 7 29 07 PM" src="https://github.com/1ifeworld/river/assets/93691906/470f334e-61e6-4722-93a3-723edad63e43">
some ideas for cleaning this code ^ up a bit:

1. pick either isNewUser or user.wallet.address to use for ur gating. you shouldnt need both. since its in the on complete hook, where by definition a user will have jsut gotten a wallet address.
2. you dont need any return statements so u can take that out
3. the old server route is in place in the checkOwnerId. plz move that to new new endpoint + tuck inside an env

2024-01-29 01:49 UTC, closed without merging